version: "3.9"
networks:
    ds-wordpress-6.7.1-net:
        driver: bridge

services:
    mysql:
        image: mysql:latest
        container_name: ds-wordpress-6.7.1-mysql
        tty: true
        ports:
            - "4208:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: wordpress
            MYSQL_USER: usuario
            MYSQL_PASSWORD: 123456
        networks:
            - ds-wordpress-6.7.1-net

    server:
        image: wordpress:latest
        container_name: ds-wordpress-6.7.1
        ports:
            - "8090:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: usuario
            WORDPRESS_DB_PASSWORD: 123456
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: ds-wordpress-6.7.1-mysql
        depends_on:
            - mysql
        networks:
            - ds-wordpress-6.7.1-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ds-phpmyadmin
        ports:
            - "4283:80"
        environment:
            PMA_HOST: ds-wordpress-6.7.1-mysql
            MYSQL_ROOT_PASSWORD: 123456
        depends_on:
            - mysql
        networks:
            - ds-wordpress-6.7.1-net
